/**
 * 中文 → 英文术语词典（用于查询扩展）。
 *
 * Halo Database 内核源码全部为英文，中文 bigram 直接 BM25 必然 0 命中。
 * 该词典把常见中文术语映射为英文关键词，使中文查询能命中英文索引。
 *
 * 匹配策略（在 expandQueryTokens 中）：
 *   - 最长匹配（"可见性" 优先于 "可见"）
 *   - 单字也能命中（"锁" → "lock"）
 *
 * 同时收集中文 bigram（用于在 principle.keywords 等中文上下文中检索）。
 */

export const CN_EN_DICT = {
  // === 动作 / 操作（通用动词）===
  '插入': 'insert',
  '删除': 'delete remove drop',
  '更新': 'update modify',
  '修改': 'modify update alter',
  '查询': 'query select',
  '检索': 'search lookup find',
  '搜索': 'search find scan',
  '查找': 'find lookup search',
  '找到': 'find locate lookup',
  '寻找': 'find locate search',
  '定位': 'locate find',
  '驱逐': 'evict drop invalidate discard',
  '丢弃': 'drop discard',
  '淘汰': 'evict invalidate replace',
  '失效': 'invalidate',
  '使无效': 'invalidate',
  '释放': 'free release',
  '回收': 'reclaim vacuum free',
  '读取': 'read fetch',
  '写入': 'write flush',
  '读': 'read',
  '写': 'write',
  '加载': 'load',
  '保存': 'save persist',
  '提交': 'commit',
  '回滚': 'abort rollback',
  '中止': 'abort cancel',
  '取消': 'cancel abort',
  '开始': 'begin start',
  '结束': 'end finish',
  '启动': 'start launch init boot',
  '停止': 'stop shutdown terminate',
  '终止': 'terminate abort kill',
  '关闭': 'close shutdown',
  '打开': 'open init',
  '切换': 'switch change',
  '分配': 'allocate alloc',
  '解析': 'parse parser',
  '分析': 'parse analyze transform',
  '优化': 'optimize planner plan',
  '执行': 'execute exec run',
  '规划': 'plan planner',
  '调度': 'schedule dispatch',
  '触发': 'trigger fire invoke',
  '唤醒': 'wakeup wake notify',
  '通知': 'notify inform',
  '请求': 'request',
  '响应': 'response respond reply',
  '等待': 'wait block',
  '阻塞': 'block',
  '加锁': 'lock acquire',
  '解锁': 'unlock release',
  '获取': 'get acquire fetch obtain',
  '设置': 'set assign',
  '注册': 'register',
  '登记': 'register record',
  '构建': 'build construct',
  '创建': 'create make new',
  '销毁': 'destroy',
  '初始化': 'init initialize',
  '清空': 'clear reset',
  '压缩': 'compress',
  '解压': 'decompress',
  '编码': 'encode',
  '解码': 'decode',
  '序列化': 'serialize',
  '反序列化': 'deserialize',
  '共享': 'shared',
  '私有': 'private',
  '本地': 'local',
  '计算': 'calculate compute eval',
  '估算': 'estimate cost',
  '估算代价': 'estimate cost',
  '统计': 'stat count',
  '处理': 'process handle',
  '检查': 'check verify inspect',
  '验证': 'verify validate check',
  '校验': 'verify check',
  '比对': 'compare cmp',
  '比较': 'compare cmp',
  '合并': 'merge combine',
  '拆分': 'split',
  '移动': 'move transfer',
  '拷贝': 'copy duplicate',
  '复制': 'replicate copy',
  '粘贴': 'paste',
  '发送': 'send transmit dispatch',
  '接收': 'receive recv accept',
  '转换': 'convert cast transform',
  '决定': 'decide choose',
  '选择': 'choose select pick',
  '过滤': 'filter qual',
  '排序': 'sort order',
  '分组': 'group',
  '聚合': 'aggregate agg',
  '连接': 'join connect connection',
  '投影': 'project',
  '限制': 'limit restrict',
  '跳过': 'skip',
  '预读': 'prefetch readahead',
  '扩展': 'extend grow add',
  '收缩': 'shrink truncate',
  '归档': 'archive',
  '备份': 'backup',
  '恢复': 'recover redo replay',
  '重做': 'redo replay',
  '重置': 'reset',
  '重启': 'restart reboot',
  '生成': 'generate create make',
  '调用': 'call invoke',
  '执行计划': 'plan',
  '跟踪': 'trace track',
  '监控': 'monitor watch',

  // === 数据结构 ===
  '堆': 'heap',
  '堆表': 'heap',
  '元组': 'tuple',
  '行': 'row tuple',
  '列': 'column attr',
  '字段': 'field attr',
  '列名': 'column name attr',
  '页面': 'page block',
  '页': 'page block',
  '块': 'block page chunk',
  '索引': 'index',
  '哈希': 'hash',
  '哈希表': 'hash table',
  'B 树': 'btree b tree',
  'B树': 'btree b tree',
  'B 树索引': 'nbtree btree b tree',
  'B树索引': 'nbtree btree b tree',
  '树': 'tree',
  '叶子': 'leaf',
  '叶子页': 'leaf page',
  '内部页': 'internal page',
  '节点': 'node',
  '链表': 'list',
  '队列': 'queue',
  '栈': 'stack',
  '缓冲': 'buffer cache',
  '缓存': 'cache buffer',
  '缓冲池': 'buffer pool',
  '缓冲区': 'buffer pool',
  '共享缓冲': 'shared buffer',
  '共享缓冲池': 'shared buffer pool',
  '共享缓存': 'shared buffer cache',
  '本地缓冲': 'local buffer',
  '数据页': 'page block',
  '脏页': 'dirty page block',
  '替换策略': 'replacement strategy policy',
  '替换': 'replace evict',
  '刷盘': 'flush write sync disk',
  '落盘': 'flush write disk',
  '写盘': 'write disk flush',
  '读盘': 'read disk',
  '磁盘': 'disk',
  '持久化': 'persist flush durable write',
  '表': 'table relation rel',
  '关系': 'relation rel',
  '视图': 'view',
  '物化视图': 'materialized view matview',
  '游标': 'cursor',
  '触发器': 'trigger',
  '函数': 'function func proc',
  '过程': 'procedure proc',
  '操作符': 'operator op',
  '类型': 'type',
  '数据类型': 'datatype data type',
  '数据': 'data datum',
  '结构': 'struct',
  '结构体': 'struct',
  '联合': 'union',
  '枚举': 'enum',
  '指针': 'pointer ptr',
  '引用': 'reference ref',
  '数组': 'array',
  '集合': 'set',
  '字典': 'dict map hash',
  '常量': 'constant const',
  '变量': 'variable var',
  '表达式': 'expression expr',
  '条件': 'condition cond where',
  '谓词': 'predicate qual',
  '范围': 'range',
  '边界': 'boundary',
  '主键': 'primary key pk',
  '外键': 'foreign key fk',
  '约束': 'constraint',
  '默认值': 'default value',
  '空值': 'null',
  'OID': 'oid',
  '标识符': 'identifier oid',
  '描述符': 'descriptor desc',
  '句柄': 'handle',

  // === 子系统 / 概念 ===
  '锁': 'lock lwlock',
  '行级锁': 'row lock tuple lock',
  '表级锁': 'table lock relation lock',
  '页级锁': 'page lock',
  '轻量锁': 'lwlock lightweight',
  '自旋锁': 'spinlock spin',
  '死锁': 'deadlock',
  '死锁检测': 'deadlock detect check',
  '检测': 'detect check',
  '锁等待': 'lock wait block',
  '事务': 'transaction xact txn',
  '子事务': 'subtransaction subxact commit abort sub',
  '子事务ID': 'subxid subtransaction',
  '两阶段提交': 'two phase commit prepared end prepare',
  '准备事务': 'prepare transaction end prepare',
  '提交日志': 'commit log clog transaction',
  '提交事务': 'commit transaction record',
  'CLog': 'clog commit log transaction',
  '事务ID': 'transaction id xid',
  '快照': 'snapshot snap data',
  '快照获取': 'get snapshot data transactional',
  '可见性': 'visibility visible',
  '可见': 'visibility visible',
  '可见性映射': 'visibility map vm',
  '可见性判断': 'visibility check',
  '检查点': 'checkpoint check point',
  '检查点机制': 'checkpoint check point',
  '日志': 'log wal journal',
  '预写日志': 'wal xlog',
  'WAL': 'wal xlog',
  'WAL 记录': 'wal record xlog',
  'WAL 缓冲': 'wal buffer xlog',
  'WAL 刷盘': 'wal flush xlog',
  'WAL 写入': 'wal write xlog insert',
  'WAL 段': 'wal segment xlog',
  'WAL segment': 'wal segment xlog',
  'WAL segment 切换': 'wal segment switch xlog',
  'WAL 切换': 'xlog switch wal',
  'wal 切换': 'xlog switch',
  '日志序列号': 'lsn',
  '日志位置': 'lsn',
  '记录': 'record log entry',
  '复制': 'replication copy',
  '流复制': 'streaming replication',
  '逻辑复制': 'logical replication',
  '逻辑解码': 'logical decoding decode',
  '同步复制': 'sync synchronous replication',
  '异步复制': 'async asynchronous replication',
  '主库': 'primary master',
  '从库': 'standby slave replica',
  '主从': 'primary standby',
  '备库': 'standby replica',
  '主备切换': 'failover switchover promote',
  '故障转移': 'failover',
  '复制槽': 'replication slot',
  '心跳': 'heartbeat',
  '崩溃': 'crash',
  '故障': 'failure fault',
  '网络': 'network socket',
  '通信': 'communication',
  '协议': 'protocol message',
  '消息': 'message',
  '握手': 'handshake startup',
  '认证': 'auth authenticate',
  '授权': 'auth privilege grant',
  '权限': 'privilege acl permission',
  '权限检查': 'privilege acl check',
  '检查表权限': 'pg_class_aclcheck aclcheck relation',
  '客户端': 'client',
  '服务端': 'server backend',
  'SSL': 'ssl tls secure',
  'TLS': 'tls ssl secure',
  'SSL 握手': 'ssl tls secure handshake open server be_tls',
  '安全连接': 'secure tls ssl',
  '接收客户端': 'recv receive client socket pq',
  '发送响应': 'send response pq putmessage',
  '发送给客户端': 'send client pq putmessage ready query',
  'ACL 检查': 'aclcheck pg_class_aclcheck',
  '权限校验': 'aclcheck privilege',
  '进程': 'process',
  '线程': 'thread',
  '后台进程': 'background worker bgwriter postmaster',
  '工作进程': 'worker bgworker',
  'postmaster 主进程': 'postmaster main server loop',
  'bgwriter 后台写进程': 'bgwriter background writer main',
  'bgwriter': 'bgwriter background writer',
  'checkpointer': 'checkpointer main',
  '检查点进程': 'checkpointer main',
  'walwriter': 'walwriter wal writer',
  'walsender': 'walsender wal sender',
  'walreceiver': 'walreceiver wal receiver',
  'autovacuum': 'autovacuum launcher worker',
  '启动子进程': 'fork child subprocess',
  '启动后台进程': 'postmaster main server loop backend init',
  '启动 postmaster': 'postmaster main server loop',
  '注册 bgworker': 'register dynamic background worker RegisterDynamic',
  'bgworker 注册': 'register dynamic background worker RegisterDynamic',
  '注册 bgworker 进程': 'register dynamic background worker RegisterDynamic',
  '注册后台工作进程': 'register background worker RegisterDynamic',
  'bgwriter 主循环': 'BackgroundWriterMain bgwriter main',
  'checkpointer 主循环': 'CheckpointerMain checkpointer main',
  'bgwriter 写脏页': 'BackgroundWriterMain buffer sync flush dirty',
  '子进程': 'child subprocess',
  '父进程': 'parent postmaster',
  '连接': 'connection client',
  '会话': 'session',
  '连接方法': 'join method',
  '顺序扫描': 'exec seqscan sequential scan',
  '索引扫描': 'exec index scan getnext',
  '位图扫描': 'bitmap scan exec',
  'TID 扫描': 'tid scan exec',
  '嵌套循环': 'nested loop join exec',
  '哈希连接': 'hash join exec node',
  '归并连接': 'merge join exec node',
  '归并排序': 'merge sort tuplesort',
  '聚合节点': 'exec agg node hash',
  '聚合': 'aggregate agg exec node',
  '执行器': 'executor exec run',
  '执行查询': 'executor run proc node',
  '谓词过滤': 'predicate filter',
  '行估计': 'row estimate',
  '代价模型': 'cost model',
  '选择度': 'selectivity',
  '基数': 'cardinality',
  '动态规划': 'dynamic programming',
  '遗传算法': 'genetic algorithm geqo',

  // === 内存管理 ===
  '内存': 'memory mem',
  '内存上下文': 'memory context mcxt',
  '内存分配': 'memory allocate palloc',
  '共享内存': 'shared memory shmem',
  '内存池': 'memory pool',

  // === Storage / smgr ===
  '表文件': 'relation file md smgr',
  '扩展表文件': 'extend file md smgr',
  '扩展块': 'extend block md smgr',
  '表块': 'table block md smgr read',
  '数据块': 'data block',
  '块号': 'block number blkno',
  '页号': 'page number',
  '偏移': 'offset',
  '存储管理': 'storage manager smgr md',
  '读取表块': 'read block md smgr',
  '读取块': 'read block md smgr',

  // === Catalog / Cache ===
  '系统表': 'catalog system',
  '系统缓存': 'syscache system cache search',
  '系统缓存查找': 'search syscache system cache',
  '关系缓存': 'relcache relation cache',
  '目录缓存': 'catcache catalog cache',
  '类型缓存': 'typcache type cache',
  '表空间': 'tablespace',
  '数据库': 'database db',
  '模式': 'schema',
  '角色': 'role',
  '用户': 'user',
  '查找表': 'find relation lookup relname get',
  '表 OID': 'relation oid relid',
  '查找表 OID': 'get relation oid relname relid',

  // === 类型 / Datum ===
  '类型转换': 'type cast convert coerce',
  '类型系统': 'type system',
  '获取类型 OID': 'typename get type oid typid',
  '类型 OID': 'type oid typid typename',
  'Datum': 'datum',

  // === Trigger ===
  'AFTER 触发器': 'after trigger',
  'BEFORE 触发器': 'before trigger',
  '语句触发器': 'statement trigger',

  // === Latch / IPC ===
  '信号': 'signal',
  '信号量': 'semaphore',
  '管道': 'pipe',
  '等待事件': 'wait event latch',
  '事件等待': 'wait event latch',
  '超时': 'timeout',
  '计时器': 'timer',
  '时钟': 'clock',
  '唤醒等待': 'set latch wakeup',
  '唤醒进程': 'set latch wakeup proc',
  '等待 latch': 'wait latch event',
  '等待事件集': 'wait event set',

  // === VACUUM / 清理 ===
  '清理': 'vacuum purge lazy',
  '死元组': 'dead tuple vacuum',
  '清理死元组': 'vacuum dead tuple lazy scan heap reclaim',
  '垃圾': 'dead garbage vacuum',
  '冻结': 'freeze frozen',
  '膨胀': 'bloat',
  '自动清理': 'autovacuum',
  '分析统计': 'analyze',
  '可见性映射': 'visibility map vm',

  // === Optimizer ===
  '代价': 'cost',
  '成本': 'cost',
  '路径': 'path',
  '计划': 'plan',
  '计划生成': 'plan generate',
  '连接顺序': 'join order',
  '估算代价': 'cost estimate',
  '估算查询代价': 'cost estimate size',
  '选择连接': 'add path joinrel joinrel',
  '连接方法选择': 'add_paths_to_joinrel sort_inner joinrel',
  '生成执行计划': 'plan generate subquery standard planner',
  '动态规划': 'dynamic programming geqo make one rel',
  '连接顺序搜索': 'join search dynamic programming',

  // === Parser ===
  '语法': 'grammar syntax',
  '语法分析': 'parse grammar syntax yyparse',
  '语法树': 'parse tree',
  '词法': 'lex token scan',
  '词法分析': 'lex scan token scanner',
  'SQL 语句': 'sql query statement',
  'SQL': 'sql query',

  // === Hook ===
  '钩子': 'hook _hook',
  'executor hook': 'ExecutorRun_hook ProcessUtility_hook',
  '执行器 hook': 'ExecutorRun_hook ExecutorStart_hook',
  'planner hook': 'planner_hook PlannerHook',
  '权限检查 hook': 'object_aclcheck pg_class_aclcheck',

  // === Access Method (AM) ===
  'btree 索引插入': '_bt_doinsert _bt_insertonpg btinsert',
  'btree 查找叶子页': '_bt_search _bt_moveright',
  'btree 查找': '_bt_search _bt_moveright',
  'hash 索引操作': 'hashbulkdelete hashgettuple hashdoinsert hashbuild',
  'hash 索引查找': 'hashgettuple _hash_first',
  'gin 索引插入': 'ginInsert ginHeapTupleInsert',
  'gin 索引查找': 'ginBeginScan gingettuple',
  'gist 索引': 'gistinsert gistgettuple',
  'brin 索引': 'brininsert bringettuple',
  'spgist 索引': 'spginsert spggettuple',
  '访问方法': 'access method am',
  'AM 注册': 'IndexAmRoutine am',

  // === 其他 ===
  '如何': '',
  '哪里': '',
  '什么': '',
  '为什么': '',
  '原理': 'principle',
  '机制': 'mechanism',
  '作用': 'purpose',
  '功能': 'feature function',
  '实现': 'implement implementation',
  '设计': 'design',
  '目的': 'purpose',
  '用处': 'purpose use',
  '示例': 'example',
  '代码': 'code',
  '源码': 'source',
  '文件': 'file',
  '位置': 'location',
  '定义': 'define definition',
  '声明': 'declare declaration',
  '调用者': 'caller',
  '被调用': 'callee',
  '相关': 'related',
  '类似': 'similar',
  '主要': 'main primary',
  '测试应用按钮': 'heap',

};

/**
 * 从中文查询抽取英文等价词。
 * 策略：先用 dict 的 keys（按长度倒序）做子串匹配，命中即替换并累加 EN 词。
 * ASCII 部分大小写不敏感（方便用户输入 "wal"/"WAL"/"oid"/"OID" 都能命中）。
 */
export function expandChineseTerms(text) {
  const enTokens = [];
  const consumed = new Set();
  // 预处理：构造 lowercase 版本的 dict keys 用于匹配，但保留原 key 映射到 entry
  const keys = Object.keys(CN_EN_DICT).sort((a, b) => b.length - a.length);
  const lowerKeys = keys.map(k => k.toLowerCase());
  const lowerText = text.toLowerCase();

  for (let ki = 0; ki < keys.length; ki++) {
    const k = keys[ki];
    if (!k) continue;
    const lk = lowerKeys[ki];
    let idx = 0;
    while ((idx = lowerText.indexOf(lk, idx)) >= 0) {
      let overlap = false;
      for (let i = idx; i < idx + lk.length; i++) {
        if (consumed.has(i)) { overlap = true; break; }
      }
      if (!overlap) {
        const en = CN_EN_DICT[k];
        if (en) {
          for (const w of en.split(/\s+/)) enTokens.push(w);
        }
        for (let i = idx; i < idx + lk.length; i++) consumed.add(i);
      }
      idx += lk.length;
    }
  }

  return enTokens;
}

export default expandChineseTerms;
